package com.fraud.repository.app.mapper;

import com.fraud.repository.app.model.AlertRecordDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AlertRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_record
     *
     * @mbg.generated
     */
    int insert(AlertRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_record
     *
     * @mbg.generated
     */
    int insertSelective(AlertRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_record
     *
     * @mbg.generated
     */
    AlertRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlertRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlertRecordDO record);

    List<AlertRecordDO> selectAlertDOByUser(@Param("user") String user,
                                            @Param("offset")int offset,
                                            @Param("limit")int limit);

    int countAlertDOByUser(@Param("user")String user);

    List<AlertRecordDO> selectAlertDOByTxID(@Param("txId") String txId);
}