package com.fraud.repository.app.mapper;

import com.fraud.repository.app.model.BlacklistDO;

import java.util.List;

public interface BlacklistDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int insert(BlacklistDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int insertSelective(BlacklistDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    BlacklistDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlacklistDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlacklistDO record);

    List<BlacklistDO> queryAllValidBlackList();

    List<BlacklistDO> queryAllValidBlackListByAccountLike(String account,
                                                          int offset,
                                                          int limit);

    Integer countValidBlackListByAccountLike(String account);

    BlacklistDO selectByAccount(String account);
}