package com.fraud.repository.app.mapper;

import com.fraud.repository.app.model.NotifyUserDO;

import java.util.List;

public interface NotifyUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_user
     *
     * @mbg.generated
     */
    int insert(NotifyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_user
     *
     * @mbg.generated
     */
    int insertSelective(NotifyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_user
     *
     * @mbg.generated
     */
    NotifyUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NotifyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotifyUserDO record);

    List<NotifyUserDO> selectNotifyUserAccount(String user,
                                               int offset,
                                               int limit);

    int countNotifyUserAccount(String user);

    List<NotifyUserDO> selectAllNotifyUser();

    NotifyUserDO selectByUserAccount(String user);

}