package com.fraud.repository.app.mapper;

import com.fraud.repository.app.model.RuleDO;

import java.util.List;

public interface RuleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbg.generated
     */
    int insert(RuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbg.generated
     */
    int insertSelective(RuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbg.generated
     */
    RuleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RuleDO record);

    List<RuleDO> selectAllRule();

    int removeCurrentRule();
}