package com.fraud.repository.app.mapper;

import com.fraud.repository.app.model.TransactionDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated
     */
    int insert(TransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated
     */
    int insertSelective(TransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated
     */
    TransactionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransactionDO record);

    int deleteByTransactionID(String transactionId);

    TransactionDO selectByTxID(String transactionId);

    List<TransactionDO> selectByTransaction(String account,
                                            String  transactionId,
                                            int offset, int limit);

    int countByTransaction(String account,
                           String  transactionId);
}