# 创建配置文件
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fraudapp
  name: fraud-config
data:
  MYSQL_URL: jdbc:mysql://mysql.fraudapp.svc.cluster.local:3306/fraud
  MYSQL_USER: root
  REDIS_HOST: redis.fraudapp.svc.cluster.local:6379
  ROCKETMQ_NAMESRV_ADDR: rocketmq-nameserver.fraudapp.svc.cluster.local:9876

#创建密钥
---
apiVersion: v1
kind: Secret
metadata:
  namespace: fraudapp
  name: fraud-secrets
type: Opaque
stringData:
  MYSQL_PASSWORD: fraud123456
  REDIS_PASSWORD: changeme1234

# 部署deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fraudapp
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: crpi-1nz5mrv3oba11j6z.cn-hangzhou.personal.cr.aliyuncs.com/fraudapp25/fraudapp:release1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: >
                -Dspring.profiles.active=k8sall
          envFrom:
            - secretRef:
                name: fraud-secrets
            - configMapRef:
                name: fraud-config
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "250m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /fraud/actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /fraud/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 30
  minReadySeconds: 10
  strategy:
    type: RollingUpdate    # 滚动更新策略
    rollingUpdate:
      maxSurge: 2          # 升级过程中最多可以比原先设置的副本数多出的数量
      maxUnavailable: 1    # 升级过程中最多有多少个POD处于无法提供服务的状态

# 创建service
---
apiVersion: v1
kind: Service
metadata:
  namespace: fraudapp
  name: fraud-service
  labels:
    app: fraud
spec:
  type: NodePort
  selector:
    app: fraud
  ports:
    - name: http
      protocol: TCP
      port: 8080            # 集群内访问的端口（Service Port）
      targetPort: 8080    # 容器中实际监听的端口
      nodePort: 30080     # 节点暴露给外部的端口（范围：30000-32767）

#自动扩容hpa机制
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraud-hpa
  namespace: fraudapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraud
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
