# redis的configmap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fraudapp
  name: redis-config
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    appendonly yes
    save 60 1000
    maxmemory 1024mb
    maxmemory-policy allkeys-lru
    

# 创建redis的配置密码
---
apiVersion: v1
kind: Secret
metadata:
  namespace: fraudapp
  name: redis-secret
type: Opaque
stringData:
  redis-password: changeme1234

#创建redis的服务
---
apiVersion: v1
kind: Service
metadata:
  namespace: fraudapp
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31379  # 可自定义访问端口
  selector:
    app: redis

# 部署redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fraudapp
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:7.2.8
          ports:
            - containerPort: 6379
          command: [ "redis-server", "--requirepass", "$(REDIS_PASSWORD)" ]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: redis-config
          configMap:
            name: redis-config