package com.fraud.repository.app.model;

import java.io.Serializable;
import java.util.Date;

public class AlertRecordDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.notify_user
     *
     * @mbg.generated
     */
    private String notifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.destination
     *
     * @mbg.generated
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.gmt_creator
     *
     * @mbg.generated
     */
    private String gmtCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.gmt_updated
     *
     * @mbg.generated
     */
    private Date gmtUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_record.gmt_updater
     *
     * @mbg.generated
     */
    private String gmtUpdater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.id
     *
     * @return the value of alert_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.id
     *
     * @param id the value for alert_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.notify_user
     *
     * @return the value of alert_record.notify_user
     *
     * @mbg.generated
     */
    public String getNotifyUser() {
        return notifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.notify_user
     *
     * @param notifyUser the value for alert_record.notify_user
     *
     * @mbg.generated
     */
    public void setNotifyUser(String notifyUser) {
        this.notifyUser = notifyUser == null ? null : notifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.destination
     *
     * @return the value of alert_record.destination
     *
     * @mbg.generated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.destination
     *
     * @param destination the value for alert_record.destination
     *
     * @mbg.generated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.type
     *
     * @return the value of alert_record.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.type
     *
     * @param type the value for alert_record.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.transaction_id
     *
     * @return the value of alert_record.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.transaction_id
     *
     * @param transactionId the value for alert_record.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.account
     *
     * @return the value of alert_record.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.account
     *
     * @param account the value for alert_record.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.amount
     *
     * @return the value of alert_record.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.amount
     *
     * @param amount the value for alert_record.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.content
     *
     * @return the value of alert_record.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.content
     *
     * @param content the value for alert_record.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.status
     *
     * @return the value of alert_record.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.status
     *
     * @param status the value for alert_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.gmt_creator
     *
     * @return the value of alert_record.gmt_creator
     *
     * @mbg.generated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.gmt_creator
     *
     * @param gmtCreator the value for alert_record.gmt_creator
     *
     * @mbg.generated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.gmt_created
     *
     * @return the value of alert_record.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.gmt_created
     *
     * @param gmtCreated the value for alert_record.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.gmt_updated
     *
     * @return the value of alert_record.gmt_updated
     *
     * @mbg.generated
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.gmt_updated
     *
     * @param gmtUpdated the value for alert_record.gmt_updated
     *
     * @mbg.generated
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_record.gmt_updater
     *
     * @return the value of alert_record.gmt_updater
     *
     * @mbg.generated
     */
    public String getGmtUpdater() {
        return gmtUpdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_record.gmt_updater
     *
     * @param gmtUpdater the value for alert_record.gmt_updater
     *
     * @mbg.generated
     */
    public void setGmtUpdater(String gmtUpdater) {
        this.gmtUpdater = gmtUpdater == null ? null : gmtUpdater.trim();
    }
}